# Generated by Django 6.0.4 on 2026-04-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ride_status_alter_ride_driver_alter_ride_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='completed',
        ),
    ]
