# Generated by Django 6.0.4 on 2026-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ride_dropoff_lat_ride_dropoff_lng_ride_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
