# Generated by Django 6.0.4 on 2026-04-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_driver_lat_driver_driver_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
